### ISSUE TITLE
Tracking ticket Update ITD steps

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#173]
- [ ] https://github.com/CodeYourFuture/curriculum/issues/1082
- [x] https://github.com/CodeYourFuture/fundamentals-blockly/pull/94
- [x] https://github.com/CodeYourFuture/curriculum/issues/956
- [ ] https://github.com/CodeYourFuture/curriculum/issues/1078
- [ ] https://github.com/CodeYourFuture/curriculum/issues/1055
