### ISSUE TITLE
Tracking ticket for off board or off repo tasks EXAMPLE FOR OPS CALL

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Ops-Programme#186]
This tracking ticket can track off board or off repo tasks related to this milestone. Tracking tickets use task lists. Task lists have these special powers

- [ ] If you paste a list of tasks and turn them into a task list
- [ ] Like so 
- [ ] Then when you hover over each list item you will get a convert to issue option
- [ ] When you paste an issue url from another repo
- [ ] https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/1494
- [ ] Then it will show you when this ticket is closed and it adds a mention to that ticket with a link back here
- [ ] When you type hash you will get a dropdown of tickets on this repo you can link
- [x] #119
- [ ] Like above - click through now to see how the tickets are now connected both ways at the top
- [ ] When you cross off this list it doesn't close the ticket

<img width="897" alt="Screenshot 2024-10-30 at 09 02 56" src="https://github.com/user-attachments/assets/7c428d65-5e7b-4e9e-aee9-9da3ac00c671">
